# Generated by Django 5.1.2 on 2024-10-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('Product', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufacture', models.TextField(blank=True, max_length=300, null=True)),
                ('Description', models.TextField(blank=True, max_length=300, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
