# Generated by Django 5.1.2 on 2024-11-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cartdb_product_name_alter_cartdb_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Message', models.TextField(blank=True, max_length=100, null=True)),
                ('Total_price', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cartdb',
            name='Postal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
