# Generated by Django 5.1.2 on 2024-11-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_orderdb_cartdb_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Postal',
        ),
        migrations.AddField(
            model_name='orderdb',
            name='Postal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
