# Generated by Django 5.1.2 on 2024-11-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_cartdb_postal_orderdb_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='Total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
